language: node_js
node_js:
  - node

jobs:
  include:
    - stage: test
      script: npm run test
    - script: npm run build

    - stage: deploy docs
      if: branch = master
      script: npm run docs
      deploy:
        provider: pages
        local-dir: docs/
        skip-cleanup: true
        github-token: $GH_TOKEN
        keep-history: true
        target-branch: gh-pages
        on:
          branch: master

    - stage: deploy npm
      if: tag IS present
      script: npm run build
      deploy:
        provider: npm
        skip-cleanup: true
        email: peculiarexpression@gmail.com
        api_key: $NPM_TOKEN
        on:
          branch: master
          tags: true
