language: node_js
node_js:
  - "node"

script:
  - npm run test
  - npm run build
after_success:
  - tasks/after_success.sh

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  target-branch: master
  on:
    branch: master
